cabal-version:      3.0
name:               publisher
version:            0.1.0.0
build-type:         Simple

executable publisher
    main-is:          Main.hs
    hs-source-dirs:   app, src
    other-modules:
        Telegram
        Config
    default-language: Haskell2010
    build-depends:
        base >= 4.14 && < 5,
        aeson,
        bytestring,
        http-client,
        http-client-tls
    ghc-options:      -Wall
